### ISSUE TITLE
RingTest throwing Unauthorized Exception

### ISSUE THREAD

**Issue by jaslend** [jonathanpotts/Ring#3]
It appears Ring have recently made changes to their API, requiring auth bearer token adding to the header for all requests.  I have managed to resolve this issue in Ring/RingClient.cs but I'm still trying to understand how to correctly create a pull request and commit my changes in GitHub (in my day job I use SVN).

**Comment by jonathanpotts** [comment]
Hi, thanks for making the change.

To create a pull request:

1. Create a fork.
2. Commit your changes to the fork.
3. Go to pull requests tab on my repo and click New pull request.
4. Select your fork as the compare (you may need to click compare across forks).
5. Your changes should be shown and then you can submit the pull request.

**Comment by jonathanpotts** [comment]
PR merged and updated package uploaded to NuGet
